language: php
php:
- 5.4
- 5.5
- hhvm
script: vendor/bin/phpunit tests/
notifications:
  hipchat:
    rooms:
      secure: fAnbDlW6fIw3J+n+t8Azsvd9i7X1r9/IhDY/0+tlABUVA3SUPVTpW0u+v3GvlQyJQcMabDztxZMqMxRj7O4ETEhLhDHxWPLTCg81r0exzGHOMjy+p1jyPnbiDhBJVX1E5hij3jSz093eTbgdrSsrCYCAPt4QVTbvrcjjxHLPUTU=
